color_list = ['#0072BD', '#D95319', '#EDB120', '#7E2F8E', '#000000', '#77AC30']
marker_list = ['o', 's', 'd', '*', '|', 'x']
HYBRID = 'hybrid'
GOSSIP = 'gossip'
LOCAL = 'local'
OPTIMIZED = 'optimized'
RANDOM = 'randomized'
PURE = 'pure'
RANDOM2 = 'randomized2'
BNB = 'branch&bound'
GRAPH = 'Kuhn Munkres'
SUBCARRIER_AWARE = 'subcarrier aware'
POWER_AWARE = 'power aware'
